### ISSUE TITLE
Some kind of auth issue? I'm aware, looking into it.

### ISSUE THREAD

**Issue by Ixitxachitl** [Ixitxachitl/Pywiki-Lite#1]
```
Traceback (most recent call last):
  File "pywiki_lite.py", line 917, in on_pubmsg
  File "pywiki_lite.py", line 669, in get_stream
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by Ixitxachitl** [comment]
looks like this might be an openai problem, it's trying to search for a streamer but the streamer is a nonetype
